# Generated by Django 5.2.4 on 2025-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningreport",
            name="average_score",
            field=models.FloatField(default=0.0, verbose_name="平均得分率"),
        ),
    ]
