# Generated by Django 5.2.4 on 2025-07-23 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="作业标题")),
                ("description", models.TextField(verbose_name="作业描述")),
                ("deadline", models.DateTimeField(verbose_name="截止时间")),
                ("total_score", models.IntegerField(verbose_name="总分")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业",
                "verbose_name_plural": "作业",
                "db_table": "assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField(verbose_name="问题内容")),
                ("reference_answer", models.TextField(verbose_name="参考答案")),
                ("score", models.IntegerField(verbose_name="分值")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assignments.assignment",
                        verbose_name="所属作业",
                    ),
                ),
            ],
            options={
                "verbose_name": "问题",
                "verbose_name_plural": "问题",
                "db_table": "questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "已提交"),
                            ("grading", "批改中"),
                            ("graded", "已批改"),
                        ],
                        default="submitted",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "obtained_score",
                    models.IntegerField(default=0, verbose_name="获得分数"),
                ),
                (
                    "overall_feedback",
                    models.TextField(blank=True, verbose_name="总体反馈"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="批改时间"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                        verbose_name="所属作业",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业提交",
                "verbose_name_plural": "作业提交",
                "db_table": "submissions",
                "ordering": ["-submitted_at"],
                "unique_together": {("assignment", "student")},
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.TextField(verbose_name="学生答案")),
                (
                    "obtained_score",
                    models.IntegerField(blank=True, null=True, verbose_name="获得分数"),
                ),
                ("ai_feedback", models.TextField(blank=True, verbose_name="AI反馈")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assignments.question",
                        verbose_name="所属问题",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assignments.submission",
                        verbose_name="所属提交",
                    ),
                ),
            ],
            options={
                "verbose_name": "答案",
                "verbose_name_plural": "答案",
                "db_table": "answers",
                "unique_together": {("submission", "question")},
            },
        ),
    ]
