# Generated by Django 5.2.4 on 2025-07-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="subject",
            field=models.CharField(default="通用", max_length=50, verbose_name="科目"),
            preserve_default=False,
        ),
    ]
