# Generated by Django 5.2.4 on 2025-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_assignment_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="answer_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="answers/", verbose_name="学生答案图片"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.TextField(blank=True, null=True, verbose_name="学生答案"),
        ),
    ]
