# Generated by Django 5.2.4 on 2025-07-23 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QAQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField(verbose_name="问题内容")),
                (
                    "subject",
                    models.CharField(blank=True, max_length=50, verbose_name="学科"),
                ),
                ("context", models.TextField(blank=True, verbose_name="问题上下文")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "问题",
                "verbose_name_plural": "问题",
                "db_table": "qa_questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QAAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ai_answer", models.TextField(verbose_name="AI回答")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="qa.qaquestion",
                        verbose_name="所属问题",
                    ),
                ),
            ],
            options={
                "verbose_name": "回答",
                "verbose_name_plural": "回答",
                "db_table": "qa_answers",
            },
        ),
    ]
