# Generated by Django 5.2.4 on 2025-07-24 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qaanswer",
            options={"verbose_name": "回答(废弃)", "verbose_name_plural": "回答(废弃)"},
        ),
        migrations.AlterModelOptions(
            name="qaquestion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "问题(废弃)",
                "verbose_name_plural": "问题(废弃)",
            },
        ),
        migrations.CreateModel(
            name="QASession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        default="通用", max_length=100, verbose_name="对话主题"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "问答会话",
                "verbose_name_plural": "问答会话",
                "db_table": "qa_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="QAMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("ai", "AI助手")],
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="qa.qasession",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "问答消息",
                "verbose_name_plural": "问答消息",
                "db_table": "qa_messages",
                "ordering": ["created_at"],
            },
        ),
    ]
